#ifndef CREDENTIALS2.H

#define CREDENTIALS2.H

#define USERNAME "EstacionMeteo"    //Nuestro usuario de Thinger.io
#define DEVICE_ID "Servidor_Meteo"  //Poner el device_ID elegido en Thinger.io
#define DEVICE_CREDENTIAL "A+aKTL!K2!Dv"    //Poner nuestra device_credencials de Thinger.io

#define ssid "RedWifiPRO"  //Nombre de red
#define password "KirguisT@N2035"  //Clave de red


#define token "1471083690:AAGfIHGM-3hLUxr82BM-F8LSRdLHt5QR1Uk"

#endif